version: 2
jobs:
  build:
    working_directory: ~/f8app
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn flow
      - run: yarn test

  android:
    working_directory: ~/f8app
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - run: yarn install
      - run: cd android && ./gradlew assembleDebug

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android
